[Job_info]
  mission = "SA_linearly_sweep"
  sample = ""

[hardware]
  model = "N9020B"
  address = '192.168.1.20'


[[measurement]]
  label = "SilentWave_noName_opti_noise"
  output = "/home/ratiswu/FastTWPATup_v4_SilentWave/after"

  res_bandwidth = 1e6
  repeat = 100
  
  [measurement.frequency]
    start = 3e9
    stop = 9e9
    points = 6001
  
  [measurement.note]
    pumping_freq = 6739e6
    pumping_power = -10.9

