[hardware]
  model = "ZNB"
  address = 'TCPIP0::192.168.1.216::inst0::INSTR'
  attenuation = 80
  port = "S21"


[[measurement]]
  label = "DR4K4"
  output = "/home/ratiswu/test/DR4K4"

  IF_bandwidth = 1000
  power = -40
  repeat = 1
  [measurement.frequency]
    start = 5.7e9
    stop = 6.1e9
    points = 5

[[pumping]]
  SG_model = "sgs100a"
  address = 'TCPIP0::192.168.1.84::inst0::INSTR'
  [pumping.frequency]
    start = 7e9
    stop = 7.4e9
    points = 101
  [pumping.power]
    start = -15
    stop = 5
    points = 20