[Job_info]
  mission = "TWPA_tuneUp"
  sample = "EmptyTest"

[Hardware]
  [Hardware.SA]
    model = "N9020B"
    address = '192.168.1.20'
  [Hardware.ROSG]
    model = "SGS100A"
    address = '192.168.1.11'
  [Hardware.PPSG]
    model = "SGS100A"
    address = '192.168.1.12'


[Readout]
  output = "/home/ratiswu/test/BypassALL"
  [Readout.a]
    label = "Ro1"
    RO_freq = 5.8e9
    span_freq = 10e6
    res_band = 1e6
    power = -40
    repeat = 2
    
  [Readout.b]
    label = "Ro2"
    RO_freq = 5.9e9
    span_freq = 10e6
    res_band = 1e6
    power = -40
    repeat = 2

[Pumping]
  [Pumping.frequency]
      start = 6.85e9
      stop = 7.125e9
      points = 100
  [Pumping.power]
      start = 2
      stop = -2
      points = 8