[Job_info]
  mission = "TWPA_tuneUp"
  sample = "DR2K3"

[Hardware]
  [Hardware.SA]
    model = "N9020B"
    address = '192.168.1.20'
  [Hardware.ROSG]
    model = "SGS100A"
    address = '192.168.1.11'
  [Hardware.PPSG]
    model = "SGS100A"
    address = '192.168.1.15'


[Readout]
  output = "/home/ratiswu/test/DR2K3_5q4cQcage/second_cali/SNR"
  [Readout.a]
    label = "Ro1"
    RO_freq = 5.8e9
    span_freq = 10e6
    res_band = 1e6
    power = -40
    repeat = 2
    
  [Readout.b]
    label = "Ro2"
    RO_freq = 6.1e9
    span_freq = 10e6
    res_band = 1e6
    power = -40
    repeat = 2

[Pumping]
  [Pumping.frequency]
      start = 6.6e9
      stop = 7.2e9
      points = 60
  [Pumping.power]
      start = 2
      stop = 7
      points = 10