[Job_info]
  mission = "TWPA_tuneUp"
  sample = "DR3K1"

[Hardware]
  [Hardware.SA]
    model = "N9020B"
    address = '192.168.1.20'
  [Hardware.ROSG]
    model = "SGS100A"
    address = '192.168.1.11'
    clock = 'int'
  [Hardware.PPSG]
    model = "SGS100A"
    address = '192.168.1.12'
    clock = 'int'


[Readout]
  output = "/home/ratiswu/test/DR3K1/SNR"
  [Readout.a]
    label = "Ro1"
    RO_freq = 5.86e9
    span_freq = 10e6
    res_band = 1e6
    power = -25
    repeat = 1
  [Readout.b]
    label = "Ro2"
    RO_freq = 5.667e9
    span_freq = 10e6
    res_band = 1e6
    power = -25
    repeat = 1

[Pumping]
  [Pumping.frequency]
      start = 7.2e9
      stop = 7.22e9
      points = 100
  [Pumping.power]
      start = 11
      stop = 13
      points = 20